### ISSUE TITLE
Gather a list of epic poems

### ISSUE THREAD

**Issue by porglezomp** [a2aaron/mario-epics#1]
Working through the wikipedia article, add section comments as you go:

- [x] Ancient epics (to 500)
- [x] 20th to 10th century BC
- [x] 8th to 6th century BC
- [x] 8th century BC to 3rd century AD
- [x] 3rd century BC
- [x] 2nd century BC
- [x] 1st century BC
- [x] 1st century AD
- [x] 2nd century
- [x] 2nd to 5th century
- [x] 3rd to 4th century
- [x] 4th century
- [x] 5th century
- [x] Medieval epics (500–1500)
- [x] 7th century
- [x] 8th to 10th century
- [x] 11th century
- [x] 12th century
- [x] 13th century
- [x] 14th century
- [x] 15th century
- [x] Modern epics (from 1500)
- [x] 16th century
- [x] 17th century
- [x] 18th century
- [x] 19th century
- [x] 20th century
- [x] 21st century
- [x] Other epics

**Comment by porglezomp** [comment]
@a2aaron could you also add the epics from a few of the centuries?

**Comment by porglezomp** [comment]
Claim the centuries you want to work on here.

**Comment by porglezomp** [comment]
I'll take the 8th century BC stuff

**Comment by porglezomp** [comment]
I will take everything up to the medieval epics.

**Comment by a2aaron** [comment]
I will do all from 7th century to 15th century (the entire Medieval epic)

**Comment by porglezomp** [comment]
I'm going to take the rest of the epics
